### ISSUE TITLE
Integration is using deprecated `DEVICE_CLASS_*` constants

### ISSUE THREAD

**Issue by frenck** [rrooggiieerr/homeassistant-xyscreens#1]
This custom integration uses deprecated `DEVICE_CLASS_*` constants in its codebase.

The `DEVICE_CLASS_*` constants have been deprecated and replaced in Home Assistant Core 2021.12 (over a year ago). I would highly suggest updating/migrating this integration to the new enums.

For example, for the device classes supported by the `sensor` platform, there is now a `SensorDeviceClass` enum. So if a sensor previously used the `DEVICE_CLASS_ENERGY` constant, it should now use `SensorDeviceClass.ENERGY`. Other platforms (like `binary_sensor`, and `number`) provide similar enumerations for their supported device classes.

The migration thus only consists of replacing constants with an enumeration member and is, therefore, very low impact and should be fairly straightforward.

If I can help resolve any questions regarding this change or migration, feel free to ask or respond to this issue. I'm happy to help!

Kindest regards,

../Frenck

**Comment by rrooggiieerr** [comment]
Thanks @frenck, I will resolve the matter.

I think I've got the `DEVICE_CLASS_*` constants from the documentation, so that probably could use an update
https://developers.home-assistant.io/docs/core/entity/cover#device-classes

**Comment by frenck** [comment]
Oh boy! I will adjust the docs, thanks for pointing that one out 👍 

../Frenck

**Comment by rrooggiieerr** [comment]
Fixed in release 0.0.5

**Comment by frenck** [comment]
Thank for the quick response @rrooggiieerr 👍 
Absolutely amazing ⭐ ⭐ ⭐ ⭐ ⭐ 

Happy New Year 🥂 

../Frenck

**Comment by rrooggiieerr** [comment]
Thanks @frenck, you too!

Since we're on the subject of covers, what ere your thoughts on this feature request of mine:
https://community.home-assistant.io/t/open-close-direction-for-projector-screens/464292

**Comment by frenck** [comment]
I not have much of an opinion on that, sorry 🤷 

I think the main case is not screens, but flipping open/close in general. There are many topics to be found on that in general, no real outcome out as of today.

../Frenck

**Comment by rrooggiieerr** [comment]
Ok, thanks!
